## Name: Bhagpreet Brar
## SID: 862013514

In [40]:
# Bhagpreet Brar SID: 862013514
#CODE WILL TAKE TIME TO RUN, IT CREATES 69 CSV'S FOR EACH SEASON AND STORES COACHING STATS
# reference: https://towardsdatascience.com/web-scraping-nba-stats-4b4f8c525994
from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd

for x in range(1951, 2020): # NBA seasons to analyze
    year = x
    # web page to scrap
    url = "https://www.basketball-reference.com/leagues/NBA_{}_coaches.html".format(year)
    # html will hold the HTML code from the website
    html = urlopen(url)
    soup = BeautifulSoup(html)

    # findALL() finds the tr elements in the HTML code
    rows = soup.findAll('tr', limit = 4)
    # getText() extracts the text from the element we specify
    col_names = [th.getText() for th in soup.findAll('tr', limit = 4)[2].findAll('th')]

    col_names[1] = 'Team'          # NA/empty columns are columns from the website that are empty
    col_names[2] = 'NA'
    col_names[3] = 'numSznsWTeam'
    col_names[4] = 'numTotSzns'
    col_names[5] = 'NA'
    col_names[6] = 'curr_games'
    col_names[7] = 'curr_wins'
    col_names[8] = 'curr_losses'
    col_names[9] = 'franch_games'
    col_names[10] = 'franch_wins'
    col_names[11] = 'franch_losses'
    col_names[12] = 'tot_games'
    col_names[13] = 'tot_wins'
    col_names[14] = 'tot_losses'
    col_names[15] = 'win_percent'
    col_names[16] = 'NA'
    col_names[17] = 'curr_pl_games'
    col_names[18] = 'curr_pl_wins'
    col_names[19] = 'curr_pl_losses'
    col_names[20] = 'franch_pl_games'
    col_names[21] = 'franch_pl_wins'
    col_names[22] = 'franch_pl_losses'
    col_names[23] = 'tot_pl_games'
    col_names[24] = 'tot_pl_wins'
    col_names[25] = 'tot_pl_losses'

    rows = soup.findAll('tr')[3:] # skips the 3 unnecessary headers/rows 

    coach_names = [[th.getText() for th in rows[i].findAll('th')] # coach names are found in the th's of html code
                for i in range(0,len(rows))]

    coach_stats = [[td.getText() for td in rows[i].findAll('td')] # every other stat found in the td's of html code
                for i in range(0,len(rows))]

    for i in range(len(coach_stats)):            # combines the coach names for their specific season stats into each row of coach_stats
        coach_stats[i].insert(0,coach_names[i][0])    

    stats = pd.DataFrame(coach_stats, columns = col_names)
    stats = stats.drop(columns = ['NA'])

    stats['Season'] = year - 1 # Adding column for the season year

    file_name = str(year - 1) + '-' + str(year) + '_NBA_Coach_Stats.csv'
    stats = stats.set_index('Coach')
    stats.to_csv(file_name) #creating 69 csv files for 1950-2018 season

In [42]:
import glob # used to read mutliple-files 
files = glob.glob('*_NBA_Coach_Stats.csv')
dfs = []
for file in files:
    df = pd.read_csv(file)
    df['filename'] = file
    dfs.append(df)
df = pd.concat(dfs, ignore_index=True)
df = df.drop(columns = 'filename')
df.to_csv('NBA_Coach_Stats_1950-2018.csv')
df

,Coach,Team,numSznsWTeam,numTotSzns,curr_games,curr_wins,curr_losses,franch_games,franch_wins,franch_losses,...,curr_pl_games,curr_pl_wins,curr_pl_losses,franch_pl_games,franch_pl_wins,franch_pl_losses,tot_pl_games,tot_pl_wins,tot_pl_losses,Season
0,Red Auerbach,BOS,13,17,80,58,22,952,620,332,...,13.0,8.0,5.0,109.0,63.0,46.0,129.0,72.0,57.0,1962
1,Jack McMahon,CHZ,1,1,38,12,26,38,12,26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1962
2,Slick Leonard,CHZ,1,1,42,13,29,42,13,29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1962
3,Charles Wolf,CIN,3,3,80,42,38,239,118,121,...,12.0,6.0,6.0,16.0,7.0,9.0,16.0,7.0,9.0,1962
4,Dick McGuire,DET,4,4,80,34,46,280,122,158,...,4.0,1.0,3.0,21.0,8.0,13.0,21.0,8.0,13.0,1962
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1685,Cotton Fitzsimmons,SAS,2,15,82,35,47,164,76,88,...,3.0,0.0,3.0,8.0,2.0,6.0,40.0,13.0,27.0,1985
1686,Bernie Bickerstaff,SEA,1,1,82,31,51,82,31,51,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1985
1687,Frank Layden,UTA,5,5,82,42,40,390,175,215,...,4.0,1.0,3.0,25.0,10.0,15.0,25.0,10.0,15.0,1985
1688,Gene Shue,WSB,13,20,69,32,37,1027,522,505,...,NaN,NaN,NaN,55.0,19.0,36.0,77.0,30.0,47.0,1985
1689,Kevin Loughery,WSB,1,14,13,7,6,13,7,6,...,5.0,2.0,3.0,5.0,2.0,3.0,48.0,25.0,23.0,1985